# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

haversine_cpp <- function(lat1, lon1, lat2, lon2) {
    .Call(`_PolandTripPlanner_haversine_cpp`, lat1, lon1, lat2, lon2)
}

haversine_matrix_cpp <- function(lats, lons) {
    .Call(`_PolandTripPlanner_haversine_matrix_cpp`, lats, lons)
}

tsp_held_karp <- function(d, start, end) {
    .Call(`_PolandTripPlanner_tsp_held_karp`, d, start, end)
}

tsp_two_opt <- function(d, start, end, max_iter = 1000L) {
    .Call(`_PolandTripPlanner_tsp_two_opt`, d, start, end, max_iter)
}

