// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// haversine_cpp
double haversine_cpp(double lat1, double lon1, double lat2, double lon2);
RcppExport SEXP _PolandTripPlanner_haversine_cpp(SEXP lat1SEXP, SEXP lon1SEXP, SEXP lat2SEXP, SEXP lon2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lat1(lat1SEXP);
    Rcpp::traits::input_parameter< double >::type lon1(lon1SEXP);
    Rcpp::traits::input_parameter< double >::type lat2(lat2SEXP);
    Rcpp::traits::input_parameter< double >::type lon2(lon2SEXP);
    rcpp_result_gen = Rcpp::wrap(haversine_cpp(lat1, lon1, lat2, lon2));
    return rcpp_result_gen;
END_RCPP
}
// haversine_matrix_cpp
NumericMatrix haversine_matrix_cpp(NumericVector lats, NumericVector lons);
RcppExport SEXP _PolandTripPlanner_haversine_matrix_cpp(SEXP latsSEXP, SEXP lonsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lats(latsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lons(lonsSEXP);
    rcpp_result_gen = Rcpp::wrap(haversine_matrix_cpp(lats, lons));
    return rcpp_result_gen;
END_RCPP
}
// tsp_held_karp
List tsp_held_karp(NumericMatrix d, int start, int end);
RcppExport SEXP _PolandTripPlanner_tsp_held_karp(SEXP dSEXP, SEXP startSEXP, SEXP endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type end(endSEXP);
    rcpp_result_gen = Rcpp::wrap(tsp_held_karp(d, start, end));
    return rcpp_result_gen;
END_RCPP
}
// tsp_two_opt
List tsp_two_opt(NumericMatrix d, int start, int end, int max_iter);
RcppExport SEXP _PolandTripPlanner_tsp_two_opt(SEXP dSEXP, SEXP startSEXP, SEXP endSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type end(endSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(tsp_two_opt(d, start, end, max_iter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PolandTripPlanner_haversine_cpp", (DL_FUNC) &_PolandTripPlanner_haversine_cpp, 4},
    {"_PolandTripPlanner_haversine_matrix_cpp", (DL_FUNC) &_PolandTripPlanner_haversine_matrix_cpp, 2},
    {"_PolandTripPlanner_tsp_held_karp", (DL_FUNC) &_PolandTripPlanner_tsp_held_karp, 3},
    {"_PolandTripPlanner_tsp_two_opt", (DL_FUNC) &_PolandTripPlanner_tsp_two_opt, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_PolandTripPlanner(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
