# Generated by using Rcpp::compileAttributes() -> do not edit by hand

tsp_held_karp <- function(d, start, end) {
    .Call(`_tripPlanner_tsp_held_karp`, d, start, end)
}

tsp_two_opt <- function(d, start, end, max_iter = 1000L) {
    .Call(`_tripPlanner_tsp_two_opt`, d, start, end, max_iter)
}

haversine_cpp <- function(lat, lon) {
    .Call(`_tripPlanner_haversine_cpp`, lat, lon)
}
