// Generated by using Rcpp::compileAttributes() -> do not edit by hand

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// tsp_held_karp
List tsp_held_karp(NumericMatrix d, int start, int end);
RcppExport SEXP _tripPlanner_tsp_held_karp(SEXP dSEXP, SEXP startSEXP, SEXP endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type end(endSEXP);
    rcpp_result_gen = Rcpp::wrap(tsp_held_karp(d, start, end));
    return rcpp_result_gen;
END_RCPP
}
// tsp_two_opt
List tsp_two_opt(NumericMatrix d, int start, int end, int max_iter);
RcppExport SEXP _tripPlanner_tsp_two_opt(SEXP dSEXP, SEXP startSEXP, SEXP endSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type end(endSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(tsp_two_opt(d, start, end, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// haversine_cpp
NumericMatrix haversine_cpp(NumericVector lat, NumericVector lon);
RcppExport SEXP _tripPlanner_haversine_cpp(SEXP latSEXP, SEXP lonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lat(latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lon(lonSEXP);
    rcpp_result_gen = Rcpp::wrap(haversine_cpp(lat, lon));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tripPlanner_tsp_held_karp", (DL_FUNC) &_tripPlanner_tsp_held_karp, 3},
    {"_tripPlanner_tsp_two_opt",   (DL_FUNC) &_tripPlanner_tsp_two_opt,   4},
    {"_tripPlanner_haversine_cpp", (DL_FUNC) &_tripPlanner_haversine_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_tripPlanner(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
