// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// haversine_cpp
double haversine_cpp(double lat1, double lon1, double lat2, double lon2);
RcppExport SEXP _PolandTripPlanner_haversine_cpp(SEXP lat1SEXP, SEXP lon1SEXP, SEXP lat2SEXP, SEXP lon2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lat1(lat1SEXP);
    Rcpp::traits::input_parameter< double >::type lon1(lon1SEXP);
    Rcpp::traits::input_parameter< double >::type lat2(lat2SEXP);
    Rcpp::traits::input_parameter< double >::type lon2(lon2SEXP);
    rcpp_result_gen = Rcpp::wrap(haversine_cpp(lat1, lon1, lat2, lon2));
    return rcpp_result_gen;
END_RCPP
}
// haversine_matrix_cpp
NumericMatrix haversine_matrix_cpp(NumericVector lats, NumericVector lons);
RcppExport SEXP _PolandTripPlanner_haversine_matrix_cpp(SEXP latsSEXP, SEXP lonsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lats(latsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lons(lonsSEXP);
    rcpp_result_gen = Rcpp::wrap(haversine_matrix_cpp(lats, lons));
    return rcpp_result_gen;
END_RCPP
}
// point_to_segment_dist_cpp
double point_to_segment_dist_cpp(double plat, double plon, double lat1, double lon1, double lat2, double lon2);
RcppExport SEXP _PolandTripPlanner_point_to_segment_dist_cpp(SEXP platSEXP, SEXP plonSEXP, SEXP lat1SEXP, SEXP lon1SEXP, SEXP lat2SEXP, SEXP lon2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type plat(platSEXP);
    Rcpp::traits::input_parameter< double >::type plon(plonSEXP);
    Rcpp::traits::input_parameter< double >::type lat1(lat1SEXP);
    Rcpp::traits::input_parameter< double >::type lon1(lon1SEXP);
    Rcpp::traits::input_parameter< double >::type lat2(lat2SEXP);
    Rcpp::traits::input_parameter< double >::type lon2(lon2SEXP);
    rcpp_result_gen = Rcpp::wrap(point_to_segment_dist_cpp(plat, plon, lat1, lon1, lat2, lon2));
    return rcpp_result_gen;
END_RCPP
}
// min_distances_to_route_cpp
NumericVector min_distances_to_route_cpp(NumericVector city_lats, NumericVector city_lons, NumericVector route_lats, NumericVector route_lons);
RcppExport SEXP _PolandTripPlanner_min_distances_to_route_cpp(SEXP city_latsSEXP, SEXP city_lonsSEXP, SEXP route_latsSEXP, SEXP route_lonsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type city_lats(city_latsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type city_lons(city_lonsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type route_lats(route_latsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type route_lons(route_lonsSEXP);
    rcpp_result_gen = Rcpp::wrap(min_distances_to_route_cpp(city_lats, city_lons, route_lats, route_lons));
    return rcpp_result_gen;
END_RCPP
}
// find_cities_near_route_cpp
LogicalVector find_cities_near_route_cpp(NumericVector city_lats, NumericVector city_lons, NumericVector route_lats, NumericVector route_lons, double radius_km);
RcppExport SEXP _PolandTripPlanner_find_cities_near_route_cpp(SEXP city_latsSEXP, SEXP city_lonsSEXP, SEXP route_latsSEXP, SEXP route_lonsSEXP, SEXP radius_kmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type city_lats(city_latsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type city_lons(city_lonsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type route_lats(route_latsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type route_lons(route_lonsSEXP);
    Rcpp::traits::input_parameter< double >::type radius_km(radius_kmSEXP);
    rcpp_result_gen = Rcpp::wrap(find_cities_near_route_cpp(city_lats, city_lons, route_lats, route_lons, radius_km));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PolandTripPlanner_haversine_cpp", (DL_FUNC) &_PolandTripPlanner_haversine_cpp, 4},
    {"_PolandTripPlanner_haversine_matrix_cpp", (DL_FUNC) &_PolandTripPlanner_haversine_matrix_cpp, 2},
    {"_PolandTripPlanner_point_to_segment_dist_cpp", (DL_FUNC) &_PolandTripPlanner_point_to_segment_dist_cpp, 6},
    {"_PolandTripPlanner_min_distances_to_route_cpp", (DL_FUNC) &_PolandTripPlanner_min_distances_to_route_cpp, 4},
    {"_PolandTripPlanner_find_cities_near_route_cpp", (DL_FUNC) &_PolandTripPlanner_find_cities_near_route_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_PolandTripPlanner(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
